# Github Action: Windows MSVC build

name: Linux Clang Build

on: [push, pull_request, fork, workflow_dispatch]

env:
  # Path to the CMake build directory.
  build: "${{ github.workspace }}/build"
  CONAN_SYSREQUIRES_MODE: "enabled"
  CONAN_USER_HOME: "${{ github.workspace }}/release/"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"
  CXX: "clang++"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1

      - name: Install CMake
        run: python ./scripts/bootstrap/install_cmake.py

      - name: Install Conan
        id: conan
        run: python ./scripts/bootstrap/install_conan.py

      - name: Cache .conan2 directory
        id: cache-conan
        uses: actions/cache@v4
        env:
          cache-name: cache-conan-modules
        with:
          path: ${{ env.CONAN_USER_HOME }}
          key: ${{ runner.os }}-builder-${{ env.cache-name }}-${{ hashFiles('**/conanfile.py') }}
          restore-keys: ${{ runner.os }}-builder-${{ env.cache-name }}-

      - name: Conan download packages
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: conan install . -b missing -pr:b=default -o samarium/*:build_tests=True -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True


      - name: CMake Configure
        run: cmake --preset=ci

      - name: CMake Build
        run: cmake --build --preset=default

      - name: CTest
        run: ctest --preset=default
